---
- name: install python for the version 2.7 to be on machine
  yum: name=python27
       enablerepo=ius
       state=present

- name: install easy_install for the python 2.7
  yum: name={{ item }} 
       enablerepo=ius
       state=present
  with_items:
    - python27-distribute
    - python27-libs
    - python27-devel
    - python27-tools

- name: install pip use from the easy_install-2.7
  easy_install: executable="easy_install-2.7" 
                name=pip
